version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      APP_ID: ${1325944}
      PRIVATE_KEY_PATH: /keys/private_key.pem
      OPENAI_API_KEY: ${AIzaSyAvrxOyAVzPVcnzxuD0mjKVDyS2bNWfC10}
    volumes:
      - ./keys:/keys
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      APP_ID: ${1325944}
      PRIVATE_KEY_PATH: /keys/private_key.pem
      OPENAI_API_KEY: ${AIzaSyAvrxOyAVzPVcnzxuD0mjKVDyS2bNWfC10}
    volumes:
      - ./keys:/keys
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

