version: "3.9"

services:
  enclov-ai:
    build: .
    ports:
      - "80:80"      # Nginx serving React frontend on 80
      - "8000:8000"  # FastAPI backend accessible on 8000 (optional)
    environment:
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
    volumes:
      - ./backend:/app/backend  # Optional for live backend dev
      - ./frontend:/app/frontend # Optional for live frontend dev
    command: /start.sh
