version: '3.8'

services:
  backend:
    build: ./backend
    container_name: enclov_backend
    env_file: .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/code
    depends_on:
      - redis

  celery:
    build: ./backend
    container_name: enclov_celery
    command: celery -A app.celery_worker worker --loglevel=info
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: enclov_redis

  nginx:
    image: nginx:stable
    container_name: enclov_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
