apiVersion: apps/v1
kind: Deployment
metadata:
  name: enclov-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enclov-ai
  template:
    metadata:
      labels:
        app: enclov-ai
    spec:
      containers:
      - name: enclov-ai
        image: your-dockerhub-username/enclov-ai:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
