name: enclov-AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install GitHub CLI
        uses: cli/cli-action@v2
      - name: Run enclov-AI PR Review
        run: bash scripts/gh/auto_review.sh ${{ github.event.pull_request.number }}
